runtime: custom
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.6

env_variables:
  TEST: "8080"

# network:
#   instance_tag: portfolio-api
#   forwarded_ports:
#     - 80:8080

# resources:
#   cpu: 2
#   memory_gb: 2.3
#   disk_size_gb: 10
#   volumes:
#     - name: ramdisk1
#       volumem_type: tmpfs
#       size_gb: 0.5

liveness_check:
  initial_delay_sec: 90
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2
readiness_check:
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
