version: '3.7'

services:
  api:
    image: portfolio-api:latest
    ports:
      - 9090:9090
    volumes:
      - ./resources:/go/src/resources
      # - ./dist:/go/src/dist
    env_file:
      - .env
  api-dev:
    image: portfolio-api-dev:latest
    ports:
      - 9090:9090
    volumes:
      - ./resources:/go/src/resources
      - ./dist:/go/src/dist
      - ./src:/go/src/src
    env_file:
      - dev.env
  portfolio-db:
    image: portfolio-db:latest
    restart: always
    # environment:
    #   POSTGRES_PASSWORD: mypassword
    volumes:
      - ./database/data:/var/lib/postgresql/data
    #   - database-folder:/var/lib/postgresql/data
      # - type: bind
      #   source: ./database/data
      #   target: /var/lib/postgresql/data
    ports:
      - 5432:5432

# volumes:
#   database-folder:

# volumes:
#   database-folder:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '\Users\Cory\Documents\Code\Portfolio\portfolio-server\database\data'
